/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNoteItemButton: typeof import('./src/components/note_item/AddNoteItemButton.vue')['default']
    AsideMenu: typeof import('./src/components/AsideMenu.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CoverLayout: typeof import('./src/components/CoverLayout.vue')['default']
    CreateNoteItem: typeof import('./src/components/note_item/CreateNoteItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    IconTransition: typeof import('./src/components/IconTransition.vue')['default']
    InputNormal: typeof import('./src/components/InputNormal.vue')['default']
    NoteItem: typeof import('./src/components/note_item/NoteItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
